namespace Tunnel.Shared;

/// <summary>
/// Manages the daemon auth token stored at ~/.tunnel/.auth.
/// The file is created with 600 permissions on first run (daemon side);
/// the CLI reads the same file to authenticate API calls.
/// No credentials ever appear in source code.
/// </summary>
public static class AuthTokenStore
{
    private static readonly string TokenPath = Path.Combine(
        Environment.GetFolderPath(Environment.SpecialFolder.UserProfile),
        ".tunnel", ".auth");

    /// <summary>
    /// Daemon: load existing token or generate a new one and persist it.
    /// Sets file permissions to 600 (owner read/write only).
    /// </summary>
    public static string LoadOrGenerate()
    {
        EnsureDir();

        if (File.Exists(TokenPath))
        {
            var existing = File.ReadAllText(TokenPath).Trim();
            if (!string.IsNullOrEmpty(existing)) return existing;
        }

        // Generate a cryptographically random 32-byte token (256-bit, URL-safe base64)
        var bytes = System.Security.Cryptography.RandomNumberGenerator.GetBytes(32);
        var token = Convert.ToBase64String(bytes)
            .Replace('+', '-').Replace('/', '_').TrimEnd('=');

        File.WriteAllText(TokenPath, token);
        SetPosixPermissions600(TokenPath);

        return token;
    }

    /// <summary>
    /// CLI: read the token generated by the daemon.
    /// Returns null if the file doesn't exist (daemon not started yet).
    /// </summary>
    public static string? Read()
    {
        if (!File.Exists(TokenPath)) return null;
        var token = File.ReadAllText(TokenPath).Trim();
        return string.IsNullOrEmpty(token) ? null : token;
    }

    private static void EnsureDir()
    {
        var dir = Path.GetDirectoryName(TokenPath)!;
        Directory.CreateDirectory(dir);
    }

    // Only meaningful on Linux/macOS — no-op on Windows dev machines
    private static void SetPosixPermissions600(string path)
    {
        try
        {
            File.SetUnixFileMode(path,
                UnixFileMode.UserRead | UnixFileMode.UserWrite);
        }
        catch (PlatformNotSupportedException) { /* Windows dev — skip */ }
        catch (Exception) { /* best effort */ }
    }
}
